### ISSUE TITLE
Dear Plastix.

### ISSUE THREAD

**Issue by Sdy36071** [Plastix/Plast-Pack#57]
@Plastix 

Dear Plastix.

I'm an user of Overcast Network.
I heard about shut down of Overcast Network, 
so I 'made' a minigame and pvp server like Overcast Network.

I need maps to run my server.
Can I use your maps?
(If you will allow me, can you send the map file..?)

I know this is not good request,
but i want to play Overcast Network more.
This is the reason that I made the server.

Please say to me if you need more informations...

I'll wait for good news.

**Comment by unixfox** [comment]
You should use the contact form on OCN : https://oc.tc/#contact or using `/msg` ingame. Github issues aren't the place to send a private message.

**Comment by Sdy36071** [comment]
@unixfox 
I already did. But they didn't answer.
and Plastix' last seen is 3 month ago.

I don't have the way to contact him.
so i choose this way.

**Comment by Brottweiler** [comment]
Email plast@oc.tc.

**Comment by CoWinkKeyDinkInc** [comment]
I have maps you may use.

https://github.com/CoWinkKeyDinkInc/CardinalPGM-Maps
