### ISSUE TITLE
improvements to container/beacon.png

### ISSUE THREAD

**Issue by plexigras** [Plastix/Plast-Pack#59]
![](https://raw.githubusercontent.com/plexigras/plexis-improvments/master/assets/minecraft/textures/gui/container/beacon.png)

better?

**Comment by Brottweiler** [comment]
Personally I don't think it looks better, it looks very flat and not pretty.

@Plastix thoughts?

**Comment by plexigras** [comment]
but is it better then the current texture?

![](https://raw.githubusercontent.com/Plastix/Plast-Pack/master/assets/minecraft/textures/gui/container/beacon.png)

**Comment by Brottweiler** [comment]
I don't think so.

**Comment by Plastix** [comment]
I haven't seen it in-game but I kind of like it.

**Comment by Brottweiler** [comment]
@Plastix 
![2017-06-08_14 49 50](https://user-images.githubusercontent.com/1613137/26929446-0c5f3278-4c5a-11e7-953b-e692d2887f69.png)

**Comment by Plastix** [comment]
@Brottweiler I like it!

**Comment by Brottweiler** [comment]
@Plastix I'll add it. 

@plexigras Would you like me to just add it manually or would you like to make a pull request?

**Comment by Plastix** [comment]
Don't forget to add attribution to the readme. Thanks @Brottweiler!

**Comment by plexigras** [comment]
@Brottweiler you can probably do it quicker manually.

**Comment by plexigras** [comment]
@Brottweiler i agreed that it was to flat so i added some shadow

**Comment by Brottweiler** [comment]
Here's how it looks ingame. I'm indifferent, what do you think @Plastix?

![2017-06-08_17 26 18](https://user-images.githubusercontent.com/1613137/26936714-b5f36434-4c6f-11e7-98a5-1b4097986d3e.png)

**Comment by Plastix** [comment]
Yep second one is better.

**Comment by Brottweiler** [comment]
Thanks! https://github.com/Plastix/Plast-Pack/commit/ea45d529ee5e36b23ad5cff2d2c240efb071f114 👍
