### ISSUE TITLE
Adding back "grass flowers"

### ISSUE THREAD

**Issue by Brottweiler** [Plastix/Plast-Pack#61]
Because we can now use CTM overlays with Optifine, we can have *both* natural textures for grass top as well as CTM overlays.

The CTM for grass top was removed in favor of natural textures, but we can have both as you can see in this image!

Questions are, **should I add this?** Also, **how rare/common should the flowers be?** I do not remember how often the flowers used to occur when it was used.

![2018-09-10_18 36 46](https://user-images.githubusercontent.com/1613137/45311199-b5e80080-b528-11e8-942c-4600922e9366.png)

**Comment by Plastix** [comment]
This looks great! 👍

**Comment by Brottweiler** [comment]
The old CTM grass had 16 textures where 4 were flowers, and the rest variants of grass (different rotations mostly), with these weights `weights=25 25 15 25 15 25 15 25 1 1 1 1 2 2 2 2`.

The four `1`s are the textures for the flowers.

In the screenshot above, the weights are `weights=1 1 1 1 200` where the `1`s are flowers and the `200` is for any block that does _not_ have the flowers. So we can decrease the `200` if we want the flowers to appear more often, like this:

![2018-09-10_22 59 20](https://user-images.githubusercontent.com/1613137/45324011-34569980-b54d-11e8-8792-6a68903b0492.png)

**Comment by Plastix** [comment]
IMO a weight of `200` does not produce enough flowers. Maybe a little less flowers than in the second picture you linked. Honestly, pick anything that you think looks good.
