### ISSUE TITLE
Donations / Patreon

### ISSUE THREAD

**Issue by srwaggon** [Plastix/Plast-Pack#64]
I love the Plastpack.

Every new Plastpack release hypes me as much as a new Minecraft Release. Minecraft to me is _incomplete_ without a new Plastpack release. This texture pack is so wonderful!

Unfortunately, I haven't found a donation button yet. Whaat?

How am I supposed to give you my money for your excellent work!?

**Comment by Brottweiler** [comment]
I'm not looking to earn anything from this. The best way you could contribute is finding bugs or sending pull requests! 

But thanks anyway! :smile:
