### ISSUE TITLE
Endermen and Spiders glow purple when joined with Sildur's Vibrant Shaders.

### ISSUE THREAD

**Issue by srwaggon** [Plastix/Plast-Pack#66]
Sorry if this falls on Sildur's shaders.
On 1.12.2, with this (wonderful) resource pack, spiders and endermen glow bright purple/pink.

![image](https://user-images.githubusercontent.com/1132359/106347450-7cd49600-6273-11eb-9101-85e407d4e0e9.png)

This doesn't seem to happen without this (once again, incredible) resource pack.

**Comment by Brottweiler** [comment]
I think this is a side-effect of using the shader. Some mobs, like Spiders and Endermen, have separate textures for their eyes. This makes the eyes **glow** in darkness, not affected by light.

Plast Pack has two textures for endermen eyes and spider eyes, which includes the whole body. This makes invisible spiders not invisible, but see-through. 

```
assets/minecraft/textures/entity/spider_eyes.png
assets/minecraft/textures/entity/enderman/enderman_eyes.png
```

If you delete these two textures, it should solve your issue.

**Comment by srwaggon** [comment]
Thanks, @Brottweiler. I have done this and it indeed fixes the visual glitch.

💯 Thanks also for the awesome explanation for the source and reasoning of this behaviour.
