### ISSUE TITLE
Some textures are not matching in the pack!

### ISSUE THREAD

**Issue by beamski44** [Plastix/Plast-Pack#68]
**Hello!**

There are two textures that I have noticed that don't match in the pack. If you use the programmer art fixes pack it adds the warped_nylium_side.png and crimson_nylium_side.png that don't match with the actual pack as the netherack texture is different.

![crimson_nylium_side](https://user-images.githubusercontent.com/94978971/143263621-272d93a7-6034-4406-a10f-3b40d36fd552.png)
![warped_nylium_side](https://user-images.githubusercontent.com/94978971/143263630-bde6674c-3cbb-4c9d-a662-c8f2f789d25a.png)

^^^^^^^
The images above are made to match the netherack texture in the pack.

**-beamski**

**Comment by Brottweiler** [comment]
Thanks! I opted for using the nylium side from Programmer Art Fix as a base since it is slightly different than vanilla.
